// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PickleballTournaments.Api.Data;

#nullable disable

namespace PickleballTournaments.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706163143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PickleballTournaments.Api.Domain.MetroCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "State")
                        .IsUnique();

                    b.ToTable("MetroCities");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AptFound")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BracketsFound")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inserted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Trigger")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScrapeRuns");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalTournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntryFee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalTournamentId");

                    b.HasIndex("DedupKey");

                    b.HasIndex("Source", "SourceId")
                        .IsUnique();

                    b.HasIndex("State", "StartDate");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.TournamentCity", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetroCityId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DistanceMiles")
                        .HasColumnType("REAL");

                    b.HasKey("TournamentId", "MetroCityId");

                    b.HasIndex("MetroCityId");

                    b.ToTable("TournamentCities");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.Tournament", b =>
                {
                    b.HasOne("PickleballTournaments.Api.Domain.Tournament", "CanonicalTournament")
                        .WithMany()
                        .HasForeignKey("CanonicalTournamentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CanonicalTournament");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.TournamentCity", b =>
                {
                    b.HasOne("PickleballTournaments.Api.Domain.MetroCity", "MetroCity")
                        .WithMany("Tournaments")
                        .HasForeignKey("MetroCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PickleballTournaments.Api.Domain.Tournament", "Tournament")
                        .WithMany("Cities")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetroCity");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.MetroCity", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("PickleballTournaments.Api.Domain.Tournament", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
